version: '3.8'

services:
  postgres-stats:
    image: postgres:15
    container_name: postgres-stats
    restart: always
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6541:5432"
    volumes:
      - postgres-stats-data:/var/lib/postgresql/data

  ewm-stats-server:
    build: ./ewm-stats/ewm-stats-server
    container_name: ewm-stats-server
    depends_on:
      - postgres-stats
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-stats:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats

  ewm-stats-client:
    build: ./ewm-stats/ewm-stats-client
    container_name: ewm-stats-client
    depends_on:
      - ewm-stats-server
    ports:
      - "9090:9090"
    environment:
      STATS_SERVER_URL: http://ewm-stats-server:9091

volumes:
  postgres-stats-data: