version: '3.8'

services:
  postgres-stats:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5432:5432"
    volumes:
      - postgres-stats-data:/var/lib/postgresql/data

  ewm-stats-server:
    build: ./ewm-stats/ewm-stats-server
    depends_on:
      - postgres-stats
    ports:
      - "9091:9091"

  ewm-stats-client:
    build: ./ewm-stats/ewm-stats-client
    depends_on:
      - ewm-stats-server
    ports:
      - "9090:9090"

volumes:
  postgres-stats-data: